debezium.sink.type=nats
debezium.sink.nats.url=nats://nats:4222
debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.offset.storage.file.filename=data/offsets.dat
debezium.source.database.hostname=postgres
debezium.source.database.port=5432
debezium.source.database.user=suiss_user
debezium.source.database.password=suiss_password
debezium.source.database.dbname=suiss_db
debezium.source.topic.prefix=suiss
debezium.source.plugin.name=pgoutput
